### ISSUE TITLE
Duda integración continua

### ISSUE THREAD

**Issue by iblancasa** [JJ/GII-2014#582]
Buenas.

Resulta que tengo una pequeña duda en cuanto al despliegue automático.

[En esta web, explican cómo desplegar automáticamente en Azure desde GitHub](http://azure.microsoft.com/en-us/documentation/articles/web-sites-publish-source-control/) y se dice:
"When updates are made to your repository, a POST request is sent to this URL, which notifies your Azure Website that the repository has been updated. At this point it retrieves the update and deploys it to your website."

En nuestro proyecto, tenemos integrado Travis para ejecutar los test. Mi duda viene por lo siguiente:
¿esa petición POST que se envía a Azure se hace después de haber pasado los test o cuando se hace un push al repositorio? Por que entiendo que, de ser de la segunda manera, no estaríamos haciéndolo bien pues, hasta que no se pasen los test, no deberíamos poder desplegar el nuevo código. En caso que siguiendo los pasos que se han descrito en esa web se despliegue pase los test o no, ¿cómo controlo que se hayan pasado los test en Travis para hacer el despliegue? Es que no encuentro nada de eso...

Al desplegar sobre un PaaS no tengo ese problema, ya que Travis permite configurar para desplegar automáticamente sobre Openshift (que es el que usamos).

**Comment by JJ** [comment]
El 14 de enero de 2015, 15:25, Israel Blancas <notifications@github.com>
escribió:

> Buenas.
>
> Resulta que tengo una pequeña duda en cuanto al despliegue automático.
>
> En esta web, explican cómo desplegar automáticamente en Azure desde GitHub
> <http://azure.microsoft.com/en-us/documentation/articles/web-sites-publish-source-control/>
> y se dice:
> "When updates are made to your repository, a POST request is sent to this
> URL, which notifies your Azure Website that the repository has been
> updated. At this point it retrieves the update and deploys it to your
> website."
>
> En nuestro proyecto, tenemos integrado Travis para ejecutar los test. Mi
> duda viene por lo siguiente:
> ¿esa petición POST que se envía a Azure se hace después de haber pasado
> los test o cuando se hace un push al repositorio? Por que entiendo que, de
> ser de la segunda manera, no estaríamos haciéndolo bien pues, hasta que no
> se pasen los test, no deberíamos poder desplegar el nuevo código. En caso
> que siguiendo los pasos que se han descrito en esa web se despliegue pase
> los test o no, ¿cómo controlo que se hayan pasado los test en Travis para
> hacer el despliegue? Es que no encuentro nada de eso...
>

Tal como yo lo entiendo, cuando se hace un push al repositorio.

También puedes hacerlo que despliegue a azure desde Travis seguramente. Es
cuestión de que lo mires. Igual que se hace a Openshift, puede hacerlo a
Azure.

**Comment by iblancasa** [comment]
Vale.
Pensaba que había alguna forma de hacerlo como en Openshift, que es dedicándole una parte especial al PaaS dentro del fichero de Travis, pero no.
Ya sé cómo hacerlo.

Gracias.
